Create save button component
swril-data-playground/swril-mobile pull request #63
Opened 2023-11-02 22:48 UTC by Kenttrann2302

- Create a save button component to save the favourite program, file, folder, ...

2023-11-03 12:45 UTC, zrwaite requested changes
There are some changes that need to be made that might be causing the issue, but the overall idea is correct. Try to get these fixes in for review before standup.

2023-11-03 12:45 UTC, zrwaite commented on src/app/components/SaveButton.tsx
> +export type SaveableEntity =
This should be in the types folder

2023-11-03 12:45 UTC, zrwaite commented on src/app/components/SaveButton.tsx
> +    changeSaveableEntity: (key: any, value: any, entity: SaveableEntity) => void
Why is there a key value thing here? Also don't use 'any'

2023-11-03 12:45 UTC, zrwaite commented on src/app/screens/Program/views/ProgramView.tsx
> +      [key]: value
You don't need this key value, just setSaveableEntity to the entire new saveable entity. the [key]: value section is unnecessary if you just set the saveableEntity correctly.

2023-11-06 21:38 UTC, zrwaite requested changes
Changes look good except for the usage in ProgramView, looks ready to add a data integration now.

2023-11-08 17:55 UTC, zrwaite commented on src/app/screens/Program/views/ProgramView.tsx
> +  const updateProgram = useCallback(async (updateEntity : SaveableEntity) => {
Why are you using a callback here? Seems like this might cause issues, it could just be a normal function.

2023-11-08 17:56 UTC, zrwaite commented on src/app/screens/Program/views/ProgramView.tsx
> +          withText={false}
Make withText optional so you don't have to add an argument for it when it is false

2023-11-08 17:56 UTC, zrwaite commented on src/app/screens/Program/views/ProgramView.tsx
> +          withText={true}
You don't need to add ={true} for true booleans, you can just have it say withText

2023-11-08 17:57 UTC, zrwaite requested changes
Looks pretty good - I need clarification on the useCallback, then you can implement this across the app.

2023-11-15 15:14 UTC, zrwaite reviewed
Looks pretty good, if the changes work on your end and you have testing extensively then you are probably good to get David to review it.

2023-11-15 15:14 UTC, zrwaite commented on src/app/screens/Poll/components/PollMenu.tsx
> +      await setPollAsFavourite(web3!, poll.id!!);
Why the `!!`

2023-11-15 16:57 UTC, Kenttrann2302 commented
@dviejokfs can you review my PR so I can merge in?

2023-11-15 17:20 UTC, dviejokfs requested changes

2023-11-15 17:20 UTC, dviejokfs commented on src/app/screens/Program/views/ProgramView.tsx
> +        {/* <TouchableOpacity
remove this comment

2023-11-15 17:20 UTC, dviejokfs commented on src/app/screens/Poll/components/PollMenu.tsx
> +          {/* <TouchableOpacity style={styles.actionButton} onPress={() => save()}>
remove this comment

2023-11-15 19:09 UTC, merged